name: Build and Commit Frontend Dist

on:
  push:
    branches:
      - main  # or your target branch

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'  # change this if needed

      - name: Install dependencies and build
        working-directory: ./frontend
        run: |
          npm install
          npm run build

      - name: Commit built dist folder
        run: |
          git config --global user.name 'github-actions[bot]'
          git config --global user.email 'github-actions[bot]@users.noreply.github.com'
          git add frontend/dist
          git commit -m 'Auto-build frontend/dist folder' || echo "No changes to commit"
          git push
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
